# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/everything/college/UCF stuff/Year 5 term 1/FPGA Design Labs/FPGA final project/vivado projects/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bm_sprite_br/bm_sprite_br.xci
# IP: The module: 'bm_sprite_br' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/everything/college/UCF stuff/Year 5 term 1/FPGA Design Labs/FPGA final project/vivado projects/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bm_sprite_br/bm_sprite_br_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bm_sprite_br'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/everything/college/UCF stuff/Year 5 term 1/FPGA Design Labs/FPGA final project/vivado projects/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bm_sprite_br/bm_sprite_br.xci
# IP: The module: 'bm_sprite_br' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/everything/college/UCF stuff/Year 5 term 1/FPGA Design Labs/FPGA final project/vivado projects/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bm_sprite_br/bm_sprite_br_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bm_sprite_br'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
